Requirement already satisfied: google-cloud-aiplatform in /Users/akitsch/code/pyenvs/db-ext-test/lib/python3.11/site-packages (1.36.4)
Requirement already satisfied: google-api-core[grpc]!=2.0.*,!=2.1.*,!=2.2.*,!=2.3.*,!=2.4.*,!=2.5.*,!=2.6.*,!=2.7.*,<3.0.0dev,>=1.32.0 in /Users/akitsch/code/pyenvs/db-ext-test/lib/python3.11/site-packages (from google-cloud-aiplatform) (2.12.0)
Requirement already satisfied: proto-plus<2.0.0dev,>=1.22.0 in /Users/akitsch/code/pyenvs/db-ext-test/lib/python3.11/site-packages (from google-cloud-aiplatform) (1.22.3)
Requirement already satisfied: protobuf!=3.20.0,!=3.20.1,!=4.21.0,!=4.21.1,!=4.21.2,!=4.21.3,!=4.21.4,!=4.21.5,<5.0.0dev,>=3.19.5 in /Users/akitsch/code/pyenvs/db-ext-test/lib/python3.11/site-packages (from google-cloud-aiplatform) (4.24.4)
Requirement already satisfied: packaging>=14.3 in /Users/akitsch/code/pyenvs/db-ext-test/lib/python3.11/site-packages (from google-cloud-aiplatform) (23.2)
Requirement already satisfied: google-cloud-storage<3.0.0dev,>=1.32.0 in /Users/akitsch/code/pyenvs/db-ext-test/lib/python3.11/site-packages (from google-cloud-aiplatform) (2.12.0)
Requirement already satisfied: google-cloud-bigquery<4.0.0dev,>=1.15.0 in /Users/akitsch/code/pyenvs/db-ext-test/lib/python3.11/site-packages (from google-cloud-aiplatform) (3.12.0)
Requirement already satisfied: google-cloud-resource-manager<3.0.0dev,>=1.3.3 in /Users/akitsch/code/pyenvs/db-ext-test/lib/python3.11/site-packages (from google-cloud-aiplatform) (1.10.4)
Requirement already satisfied: shapely<3.0.0dev in /Users/akitsch/code/pyenvs/db-ext-test/lib/python3.11/site-packages (from google-cloud-aiplatform) (1.8.5.post1)
Requirement already satisfied: googleapis-common-protos<2.0.dev0,>=1.56.2 in /Users/akitsch/code/pyenvs/db-ext-test/lib/python3.11/site-packages (from google-api-core[grpc]!=2.0.*,!=2.1.*,!=2.2.*,!=2.3.*,!=2.4.*,!=2.5.*,!=2.6.*,!=2.7.*,<3.0.0dev,>=1.32.0->google-cloud-aiplatform) (1.61.0)
Requirement already satisfied: google-auth<3.0.dev0,>=2.14.1 in /Users/akitsch/code/pyenvs/db-ext-test/lib/python3.11/site-packages (from google-api-core[grpc]!=2.0.*,!=2.1.*,!=2.2.*,!=2.3.*,!=2.4.*,!=2.5.*,!=2.6.*,!=2.7.*,<3.0.0dev,>=1.32.0->google-cloud-aiplatform) (2.23.4)
Requirement already satisfied: requests<3.0.0.dev0,>=2.18.0 in /Users/akitsch/code/pyenvs/db-ext-test/lib/python3.11/site-packages (from google-api-core[grpc]!=2.0.*,!=2.1.*,!=2.2.*,!=2.3.*,!=2.4.*,!=2.5.*,!=2.6.*,!=2.7.*,<3.0.0dev,>=1.32.0->google-cloud-aiplatform) (2.31.0)
Requirement already satisfied: grpcio<2.0dev,>=1.33.2 in /Users/akitsch/code/pyenvs/db-ext-test/lib/python3.11/site-packages (from google-api-core[grpc]!=2.0.*,!=2.1.*,!=2.2.*,!=2.3.*,!=2.4.*,!=2.5.*,!=2.6.*,!=2.7.*,<3.0.0dev,>=1.32.0->google-cloud-aiplatform) (1.59.0)
Requirement already satisfied: grpcio-status<2.0.dev0,>=1.33.2 in /Users/akitsch/code/pyenvs/db-ext-test/lib/python3.11/site-packages (from google-api-core[grpc]!=2.0.*,!=2.1.*,!=2.2.*,!=2.3.*,!=2.4.*,!=2.5.*,!=2.6.*,!=2.7.*,<3.0.0dev,>=1.32.0->google-cloud-aiplatform) (1.59.0)
Requirement already satisfied: google-cloud-core<3.0.0dev,>=1.6.0 in /Users/akitsch/code/pyenvs/db-ext-test/lib/python3.11/site-packages (from google-cloud-bigquery<4.0.0dev,>=1.15.0->google-cloud-aiplatform) (2.3.3)
Requirement already satisfied: google-resumable-media<3.0dev,>=0.6.0 in /Users/akitsch/code/pyenvs/db-ext-test/lib/python3.11/site-packages (from google-cloud-bigquery<4.0.0dev,>=1.15.0->google-cloud-aiplatform) (2.6.0)
Requirement already satisfied: python-dateutil<3.0dev,>=2.7.2 in /Users/akitsch/code/pyenvs/db-ext-test/lib/python3.11/site-packages (from google-cloud-bigquery<4.0.0dev,>=1.15.0->google-cloud-aiplatform) (2.8.2)
Requirement already satisfied: grpc-google-iam-v1<1.0.0dev,>=0.12.4 in /Users/akitsch/code/pyenvs/db-ext-test/lib/python3.11/site-packages (from google-cloud-resource-manager<3.0.0dev,>=1.3.3->google-cloud-aiplatform) (0.12.6)
Requirement already satisfied: google-crc32c<2.0dev,>=1.0 in /Users/akitsch/code/pyenvs/db-ext-test/lib/python3.11/site-packages (from google-cloud-storage<3.0.0dev,>=1.32.0->google-cloud-aiplatform) (1.5.0)
Requirement already satisfied: cachetools<6.0,>=2.0.0 in /Users/akitsch/code/pyenvs/db-ext-test/lib/python3.11/site-packages (from google-auth<3.0.dev0,>=2.14.1->google-api-core[grpc]!=2.0.*,!=2.1.*,!=2.2.*,!=2.3.*,!=2.4.*,!=2.5.*,!=2.6.*,!=2.7.*,<3.0.0dev,>=1.32.0->google-cloud-aiplatform) (5.3.1)
Requirement already satisfied: pyasn1-modules>=0.2.1 in /Users/akitsch/code/pyenvs/db-ext-test/lib/python3.11/site-packages (from google-auth<3.0.dev0,>=2.14.1->google-api-core[grpc]!=2.0.*,!=2.1.*,!=2.2.*,!=2.3.*,!=2.4.*,!=2.5.*,!=2.6.*,!=2.7.*,<3.0.0dev,>=1.32.0->google-cloud-aiplatform) (0.3.0)
Requirement already satisfied: rsa<5,>=3.1.4 in /Users/akitsch/code/pyenvs/db-ext-test/lib/python3.11/site-packages (from google-auth<3.0.dev0,>=2.14.1->google-api-core[grpc]!=2.0.*,!=2.1.*,!=2.2.*,!=2.3.*,!=2.4.*,!=2.5.*,!=2.6.*,!=2.7.*,<3.0.0dev,>=1.32.0->google-cloud-aiplatform) (4.9)
Requirement already satisfied: six>=1.5 in /Users/akitsch/code/pyenvs/db-ext-test/lib/python3.11/site-packages (from python-dateutil<3.0dev,>=2.7.2->google-cloud-bigquery<4.0.0dev,>=1.15.0->google-cloud-aiplatform) (1.16.0)
Requirement already satisfied: charset-normalizer<4,>=2 in /Users/akitsch/code/pyenvs/db-ext-test/lib/python3.11/site-packages (from requests<3.0.0.dev0,>=2.18.0->google-api-core[grpc]!=2.0.*,!=2.1.*,!=2.2.*,!=2.3.*,!=2.4.*,!=2.5.*,!=2.6.*,!=2.7.*,<3.0.0dev,>=1.32.0->google-cloud-aiplatform) (3.3.1)
Requirement already satisfied: idna<4,>=2.5 in /Users/akitsch/code/pyenvs/db-ext-test/lib/python3.11/site-packages (from requests<3.0.0.dev0,>=2.18.0->google-api-core[grpc]!=2.0.*,!=2.1.*,!=2.2.*,!=2.3.*,!=2.4.*,!=2.5.*,!=2.6.*,!=2.7.*,<3.0.0dev,>=1.32.0->google-cloud-aiplatform) (3.4)
Requirement already satisfied: urllib3<3,>=1.21.1 in /Users/akitsch/code/pyenvs/db-ext-test/lib/python3.11/site-packages (from requests<3.0.0.dev0,>=2.18.0->google-api-core[grpc]!=2.0.*,!=2.1.*,!=2.2.*,!=2.3.*,!=2.4.*,!=2.5.*,!=2.6.*,!=2.7.*,<3.0.0dev,>=1.32.0->google-cloud-aiplatform) (2.0.7)
Requirement already satisfied: certifi>=2017.4.17 in /Users/akitsch/code/pyenvs/db-ext-test/lib/python3.11/site-packages (from requests<3.0.0.dev0,>=2.18.0->google-api-core[grpc]!=2.0.*,!=2.1.*,!=2.2.*,!=2.3.*,!=2.4.*,!=2.5.*,!=2.6.*,!=2.7.*,<3.0.0dev,>=1.32.0->google-cloud-aiplatform) (2023.7.22)
Requirement already satisfied: pyasn1<0.6.0,>=0.4.6 in /Users/akitsch/code/pyenvs/db-ext-test/lib/python3.11/site-packages (from pyasn1-modules>=0.2.1->google-auth<3.0.dev0,>=2.14.1->google-api-core[grpc]!=2.0.*,!=2.1.*,!=2.2.*,!=2.3.*,!=2.4.*,!=2.5.*,!=2.6.*,!=2.7.*,<3.0.0dev,>=1.32.0->google-cloud-aiplatform) (0.5.0)
